apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -dev
resources:
# - ../../base
- loadtest-app.yaml
#- error-page.yaml
#- elastic-system-dev.yaml
# patchesStrategicMerge:
# - sandbox-app.yaml
